# Generated by Django 5.0.1 on 2024-02-06 10:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('tugilgan_yil', models.PositiveIntegerField()),
                ('davlat', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('login', models.CharField(max_length=20)),
                ('parol', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('talaba', models.BooleanField(default=True)),
                ('resm', models.FileField(blank=True, null=True, unique=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Imtixon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('daraja', models.CharField(choices=[('boshlangich', 'boshlangich'), ('orta', 'orta'), ('yuqori', 'yuqori')], max_length=20)),
                ('narx', models.IntegerField()),
                ('chegirma', models.CharField(default=0, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('narx', models.PositiveIntegerField()),
                ('yangi', models.BooleanField()),
                ('rasm', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=20)),
                ('yosh', models.CharField(max_length=20)),
                ('jins', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rejissor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('yosh', models.IntegerField()),
                ('kinolar_soni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('yosh', models.IntegerField()),
                ('jinsi', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Universiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(choices=[('HP', 'HP'), ('Acer', 'Acer'), ('Asus', 'Asus'), ('Lenovo', 'Lenovo')], max_length=100)),
                ('sana', models.DateField(auto_now_add=True)),
                ('talaba_soni', models.BigIntegerField()),
                ('sayt', models.CharField(max_length=100)),
                ('yillik', models.CharField(default=4, max_length=2)),
                ('rasmi', models.FileField(blank=True, null=True, unique=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('familiya', models.CharField(max_length=30)),
                ('jinsi', models.CharField(choices=[('ayol', 'ayol'), ('erkak', 'erkak')], max_length=10)),
                ('yosh', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Natija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(189), django.core.validators.MinValueValidator(0)])),
                ('natija', models.CharField(choices=[('budjet', 'budjet'), ('kontrakt', 'kontrakt'), ('superkontrakt', 'superkontrakt'), ('Yiqildi', 'Yiqildi')], max_length=30)),
                ('imtixon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tatu.imtixon')),
            ],
        ),
        migrations.CreateModel(
            name='Nazoratchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('kasb', models.CharField(max_length=30)),
                ('imtihon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatu.imtixon')),
            ],
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('matn', models.TextField()),
                ('sana', models.DateField()),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatu.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatu.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('yil', models.DateField()),
                ('janr', models.CharField(max_length=20)),
                ('aktyorlar', models.ManyToManyField(to='tatu.aktyor')),
                ('rejissor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatu.rejissor')),
            ],
        ),
        migrations.AddField(
            model_name='imtixon',
            name='talaba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatu.talaba'),
        ),
        migrations.CreateModel(
            name='Tanlangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatu.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatu.profil')),
            ],
        ),
        migrations.AddField(
            model_name='imtixon',
            name='universitet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatu.universiter'),
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=35)),
                ('credit', models.IntegerField()),
                ('oqituvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatu.ustoz')),
            ],
        ),
        migrations.CreateModel(
            name='Xarid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('holat', models.CharField(choices=[('tugadi', 'tugadi'), ('davomiy', 'davomiy'), ('boshlanmagan', 'boshlanmagan')], max_length=20)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatu.kurs')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatu.profil')),
            ],
        ),
    ]
